#!/bin/bash -l
#PBS -N FCI-MOC
#PBS -m n
#PBS -l nodes=1:ppn=1
#PBS -l walltime=24:00:00

run=/export/home/liangye13/soft/local/bin/python2.7

cd $PBS_O_WORKDIR

NODES=`cat $PBS_NODEFILE | uniq`
echo "--------------------------------------------------------"
echo "  JOBID: $PBS_JOBID"
echo "  The job was started at `date`"
echo "  The job was running at $NODES."
# Run gamess Job
#$run main.py > H26-31G
$run main.py > H2ccpVDZ
wait
exit 0

